language: python
python:
  - 3.7
  - 3.8
  - 3.9
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
    - "$HOME/.cache/pypoetry"

env:
  global:
    - secure: "cfecokCbYMy8VVQTvlSg02LrtFGkNsbMFyFFL55KII89tl++sY6AGu+rWpDxcv37iF8+1E/hGICDFUeOe3AyGE82wa0tz1sEIZPkmvgXNvakLTFOJh1I+p3GPKCPUxOxmeuSPYXMPtR2XnKYBnohs6nG7l/ItG91udaBQAG77gMave82dPR9jM29XYklA82HdBWYFWF8r/YuiILgQ53SNOWawQN1cMczLfZH/E29ASzVDaiIc6iKibw7NtczwND5vxQu9k7vQtAKa4m8QcinyBigZDKOQJpxf5oWe8m0YbE+bg/BCBnsydIpEzv13oi2v0ijq25h0RmMjecNoo5ssmM7MKwEojvBvnevi1pV1+LLDQdSPtjF5nEMaqmtwWpB0FY1w/LngQ5/NnleKyY0gklqqgfCBDzfOD/oROB5IeaWYcEHm/Lmz3jZxrHzhXfDED/IV3CCuSdW0bshrGggce9A6MzKuwnUDovHd7YGOroUvC2kFeN+EwFPjHtD7pFCds5uhynKY4skwPptE8IQZZuSPg6pjTMCevEteREbiD/3TSnBn736WWpSM65NC99muahmHKSSJ3Q8s9HWVTTbqy3SFu5sa2TFYGOsZNTnvBoJY+a/WWbLCB650tKY4RSa6XydxG73oRzFDsKJ5D9+HSuhX4YhM4TvoiGqyME6JKE="

services:
  - docker

before_install:
  - docker run -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD="" arangodb/arangodb:3.7.2.1
  - pip install poetry pre-commit

install:
  - poetry install

script:
  - poetry run invoke test

before_deploy:
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
  - provider: script
    skip_existing: true
    script: poetry publish --build
    on:
      branch: main
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION == 3.7"
