# Based on https://www.arangodb.com/docs/stable/appendix-error-codes.html

ERROR_ARANGO_DOCUMENT_NOT_FOUND = 1202
ERROR_ARANGO_DATA_SOURCE_NOT_FOUND = 1203
ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED = 1210
ERROR_GRAPH_NOT_FOUND = 1924
